### ISSUE TITLE
openssl error

### ISSUE THREAD

**Issue by jipenade** [gabek/supbox#1]
hello

i'm trying to run supbox and i have this error 

MacBook-Pro-de-Jean-paul:supbox jprondof$ ./supbox
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib
  Referenced from: /Users/jprondof/Desktop/supbox/./supbox
  Reason: image not found
Abort trap: 6

could you help me please ?

regards

macbook pro, catalina 10.15.7 latest

**Comment by gabek** [comment]
Looks like you might need to have OpenSSL on your machine.  I've never run into that because I guess I always have that installed.

Try giving that a shot.  You can probably just install it with Homebrew.

**Comment by jipenade** [comment]
Gotcha it’works!
I managed to install Homebrew then OpenSSL 1.1 thank you !
